### ISSUE TITLE
About the Problem of Detecting the Position and Pose of Objects

### ISSUE THREAD

**Issue by hz-ants** [MohamedNagyMostafa/KITTI-MOT.Bench-Evals#2]
Thank the author for his work！During the verification process, I found that the posture of the object is not very accurate, such as the orientation of the car facing upward. What is the reason for this and how to better solve it
![001](https://user-images.githubusercontent.com/51619755/228212867-dc45c550-8e44-4f6e-beaf-baa7c614ab34.jpg)

**Comment by MohamedNagyMostafa** [comment]
May you share settings you have used to draw the bounding box? Does this problem happen for certain evaluation file or all files?
